- name: Remove old conflicting Docker packages
  package:
    name:
      - docker
      - docker-client
      - docker-common
      - docker-engine
      - docker-io
    state: absent
  ignore_errors: yes

- name: Clean Yum metadata
  command: yum clean all

- name: Rebuild Yum cache
  command: yum makecache

- name: Clean all yum metadata
  command: yum clean metadata
  
- name: Ensure public DNS entries exist in /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: "{{ item }}"
    state: present
    insertafter: EOF
  loop:
    - "nameserver 8.8.8.8"
    - "nameserver 8.8.4.4"
  
- name: Install required dependencies
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker CE repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker CE and CLI
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Ensure docker-compose is installed
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: ansible_os_family != "Windows"

- name: Set current timestamp
  set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Check if postgresql_data_dir exists
  stat:
    path: "{{ postgresql_data_dir }}"
  register: postgres_dir_stat

- name: Rename existing postgresql_data_dir if it exists
  command: mv "{{ postgresql_data_dir }}" "{{ postgresql_data_dir }}_backup_{{ timestamp }}"
  when: postgres_dir_stat.stat.exists

- name: Create fresh postgresql_data_dir
  file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    owner: 1030
    group: 1030
    mode: '0775'

- name: Check if Artifactory directory exists
  stat:
    path: "{{ artifactory_data_dir }}"
  register: artifactory_dir_stat

- name: Rename existing artifactory_data_dir if it exists
  command: mv "{{ artifactory_data_dir }}" "{{ artifactory_data_dir }}_backup_{{ timestamp }}"
  when: artifactory_dir_stat.stat.exists

- name: Create Artifactory directory
  file:
    path: "{{ artifactory_data_dir }}"
    state: directory
    owner: 1030
    group: 1030
    mode: '0775'

- name: Create master.key with random 32-byte hex string
  shell: "openssl rand -hex 32 | tr -d '\\n' > /data/artifactory/master.key"
  args:
    creates: /data/artifactory/master.key

- name: Set ownership of master.key to UID 1030 and GID 1030
  file:
    path: /data/artifactory/master.key
    owner: "1030"
    group: "1030"

- name: Set permissions of master.key to 600
  file:
    path: /data/artifactory/master.key
    mode: '0600'

- name: Copy docker-compose.yml template
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_path }}/docker-compose.yml"

- name: Copy .env file
  copy:
    src: .env
    dest: "{{ docker_compose_path }}/.env"
    owner: 1030
    group: 1030
    mode: '0644'
#  notify: restart docker-compose

- name: restart docker-compose
  shell: |
    if docker ps --format '{% raw %}{{.Names}}{% endraw %}' | grep -qE '^(postgresql|artifactory)$'; then
      echo "Containers running. Restarting...";
      /usr/local/bin/docker-compose down && /usr/local/bin/docker-compose up -d
    else
      echo "Containers not running. Starting fresh...";
      /usr/local/bin/docker-compose up -d
    fi
  args:
    chdir: "{{ docker_compose_path }}"

- name: Wait for /data/artifactory/etc directory to exist (max 60 seconds)
  wait_for:
    path: /data/artifactory/etc
    state: present
    timeout: 60
    delay: 30

- name: Recursively set permissions and ownership for etc directory
  file:
    path: /data/artifactory/etc
    state: directory
    mode: '0775'
    owner: '1030'
    group: '1030'
    recurse: yes
